# Generated by Django 5.2 on 2025-04-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'continentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=4)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField()),
                ('flag', models.ImageField(null=True, upload_to='flags/')),
            ],
            options={
                'db_table': 'estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('estados', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estados')),
            ],
            options={
                'db_table': 'cidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patrias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('populacao', models.BigIntegerField()),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('flag', models.ImageField(null=True, upload_to='flags/')),
                ('siglas', models.CharField(max_length=4, null=True)),
                ('continentes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.continentes')),
            ],
            options={
                'db_table': 'patrias',
                'managed': True,
                'unique_together': {('id', 'continentes')},
            },
        ),
        migrations.AddField(
            model_name='estados',
            name='patrias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.patrias'),
        ),
    ]
