# Generated by Django 5.0.7 on 2024-07-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'cidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=4)),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('flag', models.ImageField(upload_to='flags/')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patrias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('capital', models.CharField(max_length=100)),
                ('populacao', models.IntegerField()),
                ('versao', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('flag', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'patrias',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='continente',
            table='continentes',
        ),
    ]
