from core.models import Patrias

# Dicionário com países e capitais
countries_and_capitals = {
    ### **Africa**
	"Algeria" : "Algiers",  
	"Angola" : "Luanda",  
	"Benin" : "Porto-Novo",  
	"Botswana" : "Gaborone",  
	"Burkina Faso" : "Ouagadougou",
	"Burundi" : "Gitega",  
	"Cabo Verde" : "Praia",  
	"Cameroon" : "Yaoundé",  
	"Central African Republic" : "Bangui",  
	"Chad" : "N'Djamena",  
	"Comoros" : "Moroni",  
	"Congo (Democratic Republic)" : "Kinshasa",  
	"Congo (Republic)" : "Brazzaville",  
	"Djibouti" : "Djibouti",  
	"Egypt" : "Cairo",  
	"Equatorial Guinea" : "Malabo",  
	"Eswatini" : "Mbabane (administrative), Lobamba (legislative)",  
	"Ethiopia" : "Addis Ababa",  
	"Gabon" : "Libreville",  
	"Gambia" : "Banjul",  
	"Ghana" : "Accra",  
	"Guinea" : "Conakry",  
	"Guinea-Bissau" : "Bissau",  
	"Ivory Coast" : "Yamoussoukro",  
	"Kenya" : "Nairobi",  
	"Lesotho" : "Maseru",  
	"Liberia" : "Monrovia",  
	"Libya" : "Tripoli",  
	"Madagascar" : "Antananarivo",  
	"Malawi" : "Lilongwe",  
	"Mali" : "Bamako",  
	"Mauritania" : "Nouakchott",  
	"Mauritius" : "Port Louis",  
	"Morocco" : "Rabat",  
	"Mozambique" : "Maputo",  
	"Namibia" : "Windhoek",  
	"Niger" : "Niamey",  
	"Nigeria" : "Abuja",  
	"Rwanda" : "Kigali",  
	"Sao Tome and Principe" : "São Tomé",  
	"Senegal" : "Dakar",  
	"Seychelles" : "Victoria",  
	"Sierra Leone" : "Freetown",  
	"Somalia" : "Mogadishu",  
	"South Africa" : "Pretoria (executive), Bloemfontein (judicial), Cape Town (legislative)",  
	"South Sudan" : "Juba",  
	"Sudan" : "Khartoum",  
	"Tanzania" : "Dodoma",  
	"Togo" : "Lomé",  
	"Tunisia" : "Tunis",  
	"Uganda" : "Kampala",  
	"Zambia" : "Lusaka",  
	"Zimbabwe" : "Harare",  

	### **Asia**
	"Afghanistan" : "Kabul",  
	"Armenia" : "Yerevan",  
	"Azerbaijan" : "Baku",  
	"Bahrain" : "Manama",  
	"Bangladesh" : "Dhaka",  
	"Bhutan" : "Thimphu",  
	"Brunei" : "Bandar Seri Begawan",  
	"Cambodia" : "Phnom Penh",  
	"China" : "Beijing",  
	"Cyprus" : "Nicosia",  
	"Georgia" : "Tbilisi",  
	"India" : "New Delhi",  
	"Indonesia" : "Jakarta",  
	"Iran" : "Tehran",  
	"Iraq" : "Baghdad",  
	"Israel" : "Jerusalem",  
	"Japan" : "Tokyo",  
	"Jordan" : "Amman",  
	"Kazakhstan" : "Astana (formerly Nur-Sultan)",  
	"Kuwait" : "Kuwait City",  
	"Kyrgyzstan" : "Bishkek",  
	"Laos" : "Vientiane",  
	"Lebanon" : "Beirut",  
	"Malaysia" : "Kuala Lumpur",  
	"Maldives" : "Malé",  
	"Mongolia" : "Ulaanbaatar",  
	"Myanmar (Burma)" : "Naypyidaw",  
	"Nepal" : "Kathmandu",  
	"North Korea" : "Pyongyang",  
	"Oman" : "Muscat",  
	"Pakistan" : "Islamabad",  
	"Palestine" : "Ramallah (administrative)",  
	"Philippines" : "Manila",  
	"Qatar" : "Doha",  
	"Saudi Arabia" : "Riyadh",  
	"Singapore" : "Singapore",  
	"South Korea" : "Seoul",  
	"Sri Lanka" : "Sri Jayawardenepura Kotte (legislative), Colombo (executive)",  
	"Syria" : "Damascus",  
	"Taiwan" : "Taipei",  
	"Tajikistan" : "Dushanbe",  
	"Thailand" : "Bangkok",  
	"Timor-Leste" : "Dili",  
	"Turkey" : "Ankara",  
	"Turkmenistan" : "Ashgabat",  
	"United Arab Emirates" : "Abu Dhabi",  
	"Uzbekistan" : "Tashkent",  
	"Vietnam" : "Hanoi",  
	"Yemen" : "Sana'a",  

	### **Europe**
	"Albania" : "Tirana",  
	"Andorra" : "Andorra la Vella",  
	"Austria" : "Vienna",  
	"Belarus" : "Minsk",  
	"Belgium" : "Brussels",  
	"Bosnia and Herzegovina" : "Sarajevo",  
	"Bulgaria" : "Sofia",  
	"Croatia" : "Zagreb",  
	"Czech Republic" : "Prague",  
	"Denmark" : "Copenhagen",  
	"Estonia" : "Tallinn",  
	"Finland" : "Helsinki",  
	"France" : "Paris",  
	"Germany" : "Berlin",  
	"Greece" : "Athens",  
	"Hungary" : "Budapest",  
	"Iceland" : "Reykjavik",  
	"Ireland" : "Dublin",  
	"Italy" : "Rome",  
	"Kosovo" : "Pristina",  
	"Latvia" : "Riga",  
	"Liechtenstein" : "Vaduz",  
	"Lithuania" : "Vilnius",  
	"Luxembourg" : "Luxembourg City",  
	"Malta" : "Valletta",  
	"Moldova" : "Chișinău",  
	"Monaco" : "Monaco",  
	"Montenegro" : "Podgorica",  
	"Netherlands" : "Amsterdam",  
	"North Macedonia" : "Skopje",  
	"Norway" : "Oslo",  
	"Poland" : "Warsaw" , 
	"Portugal" : "Lisbon",  
	"Romania" : "Bucharest",  
	"Russia" : "Moscow",  
	"San Marino" : "San Marino",  
	"Serbia" : "Belgrade",  
	"Slovakia" : "Bratislava",  
	"Slovenia" : "Ljubljana",  
	"Spain" : "Madrid",  
	"Sweden" : "Stockholm",  
	"Switzerland" : "Bern",  
	"Ukraine" : "Kyiv",  
	"United Kingdom" : "London",  
	"Vatican City" : "Vatican City",  

	### **North America**
	"Antigua and Barbuda" : "St. John's",  
	"Bahamas" : "Nassau",  
	"Barbados" : "Bridgetown",  
	"Belize" : "Belmopan",  
	"Canada" : "Ottawa",  
	"Costa Rica" : "San José",  
	"Cuba" : "Havana",  
	"Dominica" : "Roseau",  
	"Dominican Republic" : "Santo Domingo",  
	"El Salvador" : "San Salvador",  
	"Grenada" : "St. George's",  
	"Guatemala" : "Guatemala City",  
	"Haiti" : "Port-au-Prince",  
	"Honduras" : "Tegucigalpa",  
	"Jamaica" : "Kingston",  
	"Mexico" : "Mexico City",  
	"Nicaragua" : "Managua",  
	"Panama" : "Panama City",  
	"Saint Kitts and Nevis" : "Basseterre",  
	"Saint Lucia" : "Castries",  
	"Saint Vincent and the Grenadines" : "Kingstown",  
	"Trinidad and Tobago" : "Port of Spain",  
	"United States" : "Washington, D.C.",  

	### **South America**
	"Argentina" : "Buenos Aires",  
	"Bolivia" : "Sucre (constitutional), La Paz (administrative)",  
	"Brazil" : "Brasília",  
	"Chile" : "Santiago",  
	"Colombia" : "Bogotá",  
	"Ecuador" : "Quito",  
	"Guyana" : "Georgetown",  
	"Paraguay" : "Asunción",  
	"Peru" : "Lima",  
	"Suriname" : "Paramaribo",  
	"Uruguay" : "Montevideo",  
	"Venezuela" : "Caracas",  

	### **Oceania**
	"Australia" : "Canberra",  
	"Fiji" : "Suva",  
	"Kiribati" : "South Tarawa",  
	"Marshall Islands" : "Majuro",  
	"Micronesia" : "Palikir",  
	"Nauru" : "Yaren (de facto)",  
	"New Zealand" : "Wellington",  
	"Palau" : "Ngerulmud",  
	"Papua New Guinea" : "Port Moresby",  
	"Samoa" : "Apia",  
	"Solomon Islands" : "Honiara",  
	"Tonga" : "Nukuʻalofa",  
	"Tuvalu" : "Funafuti",  
	"Vanuatu" : "Port Vila",
}
def update_capitais():
    print("[INFO] Iniciando a atualização das capitais...")
    total_atualizado = 0
    total_nao_encontrado = 0
    
    # Busca todos os registros da tabela 'Patrias'
    for patria in Patrias.objects.all():
        # Verifica se o nome de um país está no dicionário
        capital = countries_and_capitals.get(patria.nome)
        if capital:
            patria.capital = capital
            patria.save() # Salva a alteração no banco de dados
            total_atualizado += 1
            print(f"[INFO] Capital atualizada: {patria.nome} -> {capital}")
        else:
            total_nao_encontrado += 1
            print(f"[AVISO] País não encontrado no dicionário: {patria.nome}")
    print(f"[INFO] Atualização concluida. Capitais atualizadas: {total_atualizado}")
   
# Executa a função
update_capitais() 