from core.models import Patrias

# Dicionário com países e continentes
countries_and_continentes = {
    
    ### **Africa** 3
	"Algeria" : 3,  
	"Angola" : 3,  
	"Benin" : 3,  
	"Botswana" : 3,  
	"Burkina Faso" : 3,
	"Burundi" : 3,  
	"Cabo Verde" : 3,  
	"Cameroon" : 3,  
	"Central African Republic" : 3,  
	"Chad" : 3,  
	"Comoros" : 3,  
	"Congo (Democratic Republic)" : 3,  
	"Congo (Republic)" : 3,  
	"Djibouti" : 3,  
	"Egypt" : 3,  
	"Equatorial Guinea" : 3,  
	"Eswatini" : 3,  
	"Ethiopia" : 3,  
	"Gabon" : 3,  
	"Gambia" : 3,  
	"Ghana" : 3,  
	"Guinea" : 3,  
	"Guinea-Bissau" : 3,  
	"Ivory Coast" : 3,  
	"Kenya" : 3,  
	"Lesotho" : 3,  
	"Liberia" : 3,  
	"Libya" : 3,  
	"Madagascar" : 3,  
	"Malawi" : 3,  
	"Mali" : 3,  
	"Mauritania" : 3,  
	"Mauritius" : 3,  
	"Morocco" : 3,  
	"Mozambique" : 3,  
	"Namibia" : 3,  
	"Niger" : 3,  
	"Nigeria" : 3,  
	"Rwanda" : 3,  
	"Sao Tome and Principe" : 3,  
	"Senegal" : 3,  
	"Seychelles" : 3,  
	"Sierra Leone" : 3,  
	"Somalia" : 3,  
	"South Africa" : 3,  
	"South Sudan" : 3,  
	"Sudan" : 3,  
	"Tanzania" : 3,  
	"Togo" : 3,  
	"Tunisia" : 3,  
	"Uganda" : 3,  
	"Zambia" : 3,  
	"Zimbabwe" : 3,  

	### **Asia** 1
	"Afghanistan" : 1,  
	"Armenia" : 1,  
	"Azerbaijan" : 1,  
	"Bahrain" : 1,  
	"Bangladesh" : 1,  
	"Bhutan" : 1,  
	"Brunei" : 1,  
	"Cambodia" : 1,  
	"China" : 1,  
	"Cyprus" : 1,  
	"Georgia" : 1,  
	"India" : 1,  
	"Indonesia" : 1,  
	"Iran" : 1,  
	"Iraq" : 1,  
	"Israel" : 1,  
	"Japan" : 1,  
	"Jordan" : 1,  
	"Kazakhstan" : 1,  
	"Kuwait" : 1,  
	"Kyrgyzstan" : 1,  
	"Laos" : 1,  
	"Lebanon" : 1,  
	"Malaysia" : 1,  
	"Maldives" : 1,  
	"Mongolia" : 1,  
	"Myanmar (Burma)" : 1,  
	"Nepal" : 1,  
	"North Korea" : 1,  
	"Oman" : 1,  
	"Pakistan" : 1,  
	"Palestine" : 1,  
	"Philippines" : 1,  
	"Qatar" : 1,  
	"Saudi Arabia" : 1,  
	"Singapore" : 1,  
	"South Korea" : 1,  
	"Sri Lanka" : 1,  
	"Syria" : 1,  
	"Taiwan" : 1,  
	"Tajikistan" : 1,  
	"Thailand" : 1,  
	"Timor-Leste" : 1,  
	"Turkey" : 1,  
	"Turkmenistan" : 1,  
	"United Arab Emirates" : 1,  
	"Uzbekistan" : 1,  
	"Vietnam" : 1,  
	"Yemen" : 1,  

	### **Europe** 5
	"Albania" : 5,  
	"Andorra" : 5,  
	"Austria" : 5,  
	"Belarus" : 5,  
	"Belgium" : 5,  
	"Bosnia and Herzegovina" : 5,  
	"Bulgaria" : 5,  
	"Croatia" : 5,  
	"Czech Republic" : 5,  
	"Denmark" : 5,  
	"Estonia" : 5,  
	"Finland" : 5,  
	"France" : 5,  
	"Germany" : 5,  
	"Greece" : 5,  
	"Hungary" : 5,  
	"Iceland" : 5,  
	"Ireland" : 5,  
	"Italy" : 5,  
	"Kosovo" : 5,  
	"Latvia" : 5,  
	"Liechtenstein" : 5,  
	"Lithuania" : 5,  
	"Luxembourg" : 5,  
	"Malta" : 5,  
	"Moldova" : 5,  
	"Monaco" : 5,  
	"Montenegro" : 5,  
	"Netherlands" : 5,  
	"North Macedonia" : 5,  
	"Norway" : 5,  
	"Poland" : 5, 
	"Portugal" : 5,  
	"Romania" : 5,  
	"Russia" : 5,  
	"San Marino" : 5,  
	"Serbia" : 5,  
	"Slovakia" : 5,  
	"Slovenia" : 5,  
	"Spain" : 5,  
	"Sweden" : 5,  
	"Switzerland" : 5,  
	"Ukraine" : 5,  
	"United Kingdom" : 5,  
	"Vatican City" : 5,  

	### **North America** 2
	"Canada" : 2,
	"Mexico" : 2,
	"United States" : 2,
    "Puerto Rico" : 2, 
	
	### **Central America** 7
     "Antigua and Barbuda" : 7,
	"Bahamas" : 7,  
	"Barbados" : 7,  
	"Belize" : 7,  
	"Costa Rica" : 7,  
	"Cuba" : 7,  
	"Dominica" : 7,  
	"Dominican Republic" : 7,  
	"El Salvador" : 7,  
	"Grenada" : 7,  
	"Guatemala" : 7,  
	"Haiti" : 7,  
	"Honduras" : 7,  
	"Jamaica" : 7,  
	"Nicaragua" : 7,  
	"Panama" : 7,  
	"Saint Kitts and Nevis" : 7,  
	"Saint Lucia" : 7,  
	"Saint Vincent and the Grenadines" : 7,  
	"Trinidad and Tobago" : 7,  
	  

	### **South America** 8
	"Argentina" : 8,  
	"Bolivia" : 8,  
	"Brazil" : 8,  
	"Chile" : 8,  
	"Colombia" : 8,  
	"Ecuador" : 8,  
	"Guyana" : 8,  
	"Paraguay" : 8,  
	"Peru" : 8,  
	"Suriname" : 8,  
	"Uruguay" : 8,  
	"Venezuela" : 8,  

	### **Oceania** 6
	"Australia" : 6,  
	"Fiji" : 6,  
	"Kiribati" : 6,  
	"Marshall Islands" : 6,  
	"Micronesia" : 6,  
	"Nauru" : 6,  
	"New Zealand" : 6,  
	"Palau" : 6,  
	"Papua New Guinea" : 6,  
	"Samoa" : 6,  
	"Solomon Islands" : 6,  
	"Tonga" : 6,  
	"Tuvalu" : 6,  
	"Vanuatu" : 6,

}

def update_continentes():
    print("[INFO] Iniciando a atualização das capitais...")
    total_atualizado = 0
    total_nao_encontrado = 0
    
    # Busca todos os registros da tabela 'Patrias'
    for patria in Patrias.objects.all():
        # Verifica se o nome de um país está no dicionário
        continentes_id = countries_and_continentes.get(patria.nome)
        if continentes_id:
            patria.continentes_id = continentes_id
            patria.save() # Salva a alteração no banco de dados
            total_atualizado += 1
            print(f"[INFO] Continente atualizado: {patria.nome} -> {continentes_id}")
        else:
            total_nao_encontrado += 1
            print(f"[AVISO] País não encontrado no dicionário: {patria.nome}")
    print(f"[INFO] Atualização concluida. Capitais atualizadas: {total_atualizado}")
   
# Executa a função
update_continentes() 