import sys
import os
import django
# Configurar o caminho do projeto e o Django
sys.path.append("/home/carlos/Desenvolvimento/Python/Workspace/earthProject")
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'terra.settings')
django.setup()
from core.models import Patrias

bandeiras = {
"Åland Islands" : "/imagens_png/ax.png", 
"Albania" : "imagens_png/al.png", 
"Algeria" : "imagens_png/dz.png",
"American Samoa" : "imagens_png/as.png",
"Andorra" : "imagens_png/ad.png",
"Angola" : "imagens_png/ao.png",
"Anguilla" : "imagens_png/ai.png",
"Antarctica" : "imagens_png/aq.png",
"Antigua and Barbuda" : "imagens_png/ag.png",
"Argentina" : "imagens_png/ar.png",
"Armenia" : "imagens_png/am.png",
"Aruba" : "imagens_png/aw.png",
"Australia" : "imagens_png/au.png",
"Austria" : "imagens_png/at.png",
"Azerbaijan" : "imagens_png/az.png",
"Bahamas" : "imagens_png/bs.png",
"Bahrain" : "imagens_png/bh.png",
"Bangladesh" : "imagens_png/bd.png",
"Barbados" : "imagens_png/bb.png",
"Belarus" : "imagens_png/by.png",
"Belgium" : "imagens_png/be.png",
"Belize" : "imagens_png/bz.png",
"Benin" : "imagens_png/bj.png",
"Bermuda" : "imagens_png/bm.png",
"Bhutan" : "imagens_png/bt.png",
"Bolivia" : "imagens_png/bo.png",
"Bosnia and Herzegovina" : "imagens_png/ba.png",
"Botswana" : "imagens_png/bw.png",
"Bouvet Island" : "imagens_png/bv.png",
"Brazil" : "imagens_png/br.png",
"British Indian Ocean Territory" : "imagens_png/io.png",
"Brunei" : "imagens_png/bn.png",
"Bulgaria" : "imagens_png/bg.png",
"Burkina Faso" : "imagens_png/bf.png",
"Burundi" : "imagens_png/bi.png",
"Cambodia" : "imagens_png/kh.png",
"Cameroon" : "imagens_png/cm.png",
"Canada" : "imagens_png/ca.png",
"Cape Verde" : "imagens_png/cv.png",
"Caribbean Netherlands" : "imagens_png/bq.png",
"Cayman Islands" : "imagens_png/ky.png",
"Central African Republic" : "imagens_png/cf.png",
"Chad" : "imagens_png/td.png",
"Chile" : "imagens_png/cl.png",
"China" : "imagens_png/cn.png",
"Christmas Island" : "imagens_png/cx.png",
"Cocos (Keeling) Islands" : "imagens_png/cc.png",
"Colombia" : "imagens_png/co.png",
"Comoros" : "imagens_png/km.png",
"Republic of the Congo" : "imagens_png/cg.png",
"DR Congo" : "imagens_png/cd.png",
"Cook Islands" : "imagens_png/ck.png",
"Costa Rica" : "imagens_png/cr.png",
"Côte d'Ivoire (Ivory Coast)" : "imagens_png/ci.png",
"Croatia" : "imagens_png/hr.png",
"Cuba" : "imagens_png/cu.png",
"Curaçao" : "imagens_png/cw.png",
"Cyprus" : "imagens_png/cy.png",
"Czechia" : "imagens_png/cz.png",
"Denmark" : "imagens_png/dk.png",
"Djibouti" : "imagens_png/dj.png",
"Dominica" : "imagens_png/dm.png",
"Dominican Republic" : "imagens_png/do.png",
"Ecuador" : "imagens_png/ec.png",
"Egypt" : "imagens_png/eg.png",
"El Salvador" : "imagens_png/sv.png",
"England" : "imagens_png/gb-eng.png",
"Equatorial Guinea" : "imagens_png/gq.png",
"Eritrea" : "imagens_png/er.png",
"Estonia" : "imagens_png/ee.png",
"Eswatini (Swaziland)" : "imagens_png/sz.png",
"Ethiopia" : "imagens_png/et.png",
"Falkland Islands" : "imagens_png/fk.png",
"Faroe Islands" : "imagens_png/fo.png",
"Fiji" : "imagens_png/fj.png",
"Finland" : "imagens_png/fi.png",
"France" : "imagens_png/fr.png",
"French Guiana" : "imagens_png/gf.png",
"French Polynesia" : "imagens_png/pf.png",
"French Southern and Antarctic Lands" : "imagens_png/tf.png",
"Gabon" : "imagens_png/ga.png",
"Gambia" : "imagens_png/gm.png",
"Georgia" : "imagens_png/ge.png",
"Germany" : "imagens_png/de.png",
"Ghana" : "imagens_png/gh.png",
"Gibraltar" : "imagens_pngimagens_png/gi.png",
"Greece" : "imagens_png/gr.png",
"Greenland" : "imagens_png/gl.png",
"Grenada" : "imagens_png/gd.png",
"Guadeloupe" : "imagens_png/gp.png",
"Guam" : "imagens_png/gu.png",
"Guatemala" : "imagens_png/gt.png",
"Guernsey" : "imagens_png/gg.png",
"Guinea" : "imagens_png/gn.png",
"Guinea-Bissau" : "imagens_png/gw.png",
"Guyana" : "imagens_png/gy.png",
"Haiti" : "imagens_png/ht.png",
"Heard Island and McDonald Islands" : "imagens_png/hm.png",
"Honduras" : "imagens_png/hn.png",
"Hong Kong" : "imagens_png/hk.png",
"Hungary" : "imagens_png/hu.png", 
"Iceland" : "imagens_png/is.png",
"India" : "imagens_png/in.png",
"Indonesia" : "imagens_png/id.png",
"Iran" : "imagens_png/ir.png",
"Iraq" : "imagens_png/iq.png",
"Ireland" : "imagens_png/ie.png",
"Isle of Man" : "imagens_png/im.png",
"Israel" : "imagens_png/il.png",
"Italy" : "imagens_png/it.png",
"Jamaica" : "imagens_png/jm.png",
"Japan" : "imagens_png/jp.png",
"Jersey" : "imagens_png/je.png",
"Jordan" : "imagens_png/jo.png", 
"Kazakhstan" : "imagens_png/kz.png",
"Kenya" : "imagens_png/ke.png",
"Kiribati" : "imagens_png/ki.png",
"North Korea" : "imagens_png/kp.png",
"South Korea" : "imagens_png/kr.png",
"Kosovo" : "imagens_png/xk.png",
"Kuwait" : "imagens_png/kw.png",
"Kyrgyzstan" : "imagens_png/kg.png",
"Laos" : "imagens_pngimagens_png/la.png",
"Latvia" : "imagens_png/lv.png",
"Lebanon" : "imagens_png/lb.png",
"Lesotho" : "imagens_png/ls.png",
"Liberia" : "imagens_png/lr.png",
"Libya" : "imagens_png/ly.png",
"Liechtenstein" : "imagens_png/li.png",
"Lithuania" : "imagens_png/lt.png",
"Luxembourg" : "imagens_png/lu.png",
"Macau" : "imagens_png/mo.png",
"Madagascar" : "imagens_png/mg.png",
"Malawi" : "imagens_png/mw.png",
"Malaysia" : "imagens_png/my.png",
"Maldives" : "imagens_png/mv.png",
"Mali" : "imagens_png/ml.png",
"Malta" : "imagens_png/mt.png",
"Marshall Islands" : "imagens_png/mh.png",
"Martinique" : "imagens_png/mq.png",
"Mauritania" : "imagens_png/mr.png",
"Mauritius" : "imagens_png/mu.png",
"Mayotte" : "imagens_png/yt.png",
"Mexico" : "imagens_png/mx.png",
"Micronesia" : "imagens_png/fm.png",
"Moldova" : "imagens_png/md.png",
"Monaco" : "imagens_png/mc.png",
"Mongolia" : "imagens_png/mn.png",
"Montenegro" : "imagens_png/me.png",
"Montserrat" : "imagens_png/ms.png",
"Morocco" : "imagens_png/ma.png",
"Mozambique" : "imagens_png/mz.png",
"Myanmar" : "imagens_png/mm.png",
"Namibia" : "imagens_png/na.png",
"Nauru" : "imagens_png/nr.png",
"Nepal" : "imagens_png/np.png",
"Netherlands" : "imagens_png/nl.png",
"New Caledonia" : "imagens_png/nc.png",
"New Zealand" : "imagens_png/nz.png",
"Nicaragua" : "imagens_png/ni.png",
"Niger" : "imagens_png/ne.png",
"Nigeria" : "imagens_png/ng.png",
"Niue" : "imagens_png/nu.png",
"Norfolk Island" : "imagens_png/nf.png",
"North Macedonia" : "imagens_png/mk.png",
"Northern Ireland" : "imagens_png/gb-nir.png",
"Northern Mariana Islands" : "imagens_png/mp.png",
"Norway" : "imagens_png/no.png",
"Oman" : "imagens_png/om.png",
"Pakistan" : "imagens_png/pk.png",
"Palau" : "imagens_png/pw.png",
"Palestine" : "imagens_png/ps.png",
"Panama" : "imagens_png/pa.png",
"Papua New Guinea" : "imagens_png/pg.png",
"Paraguay" : "imagens_png/py.png",
"Peru" : "imagens_png/pe.png",
"Philippines" : "imagens_png/ph.png",
"Pitcairn Islands" : "imagens_png/pn.png",
"Poland" : "imagens_png/pl.png",
"Portugal" : "imagens_png/pt.png",
"Puerto Rico" : "imagens_png/pr.png",
"Qatar" : "imagens_png/qa.png",
"Réunion" : "imagens_png/re.png",
"Romania" : "imagens_png/ro.png",
"Russia" : "imagens_png/ru.png",
"Rwanda" : "imagens_png/rw.png",
"Saint Barthélemy" : "imagens_png/bl.png",
"Saint Helena, Ascension and Tristan da Cunha" : "imagens_png/sh.png",
"Saint Kitts and Nevis" : "imagens_png/kn.png",
"Saint Lucia" : "imagens_png/lc.png",
"Saint Martin" : "imagens_png/mf.png",
"Saint Pierre and Miquelon" : "imagens_png/pm.png",
"Saint Vincent and the Grenadines" : "imagens_png/vc.png",
"Samoa" : "imagens_png/ws.png",
"San Marino" : "imagens_png/sm.png",
"São Tomé and Príncipe" : "imagens_png/st.png",
"Saudi Arabia" : "imagens_png/sa.png",
"Scotland" : "imagens_png/gb-sct.png",
"Senegal" : "imagens_png/sn.png",
"Serbia" : "imagens_png/rs.png",
"Seychelles" : "imagens_png/sc.png",
"Sierra Leone" : "imagens_png/sl.png",
"Singapore" : "imagens_png/sg.png",
"Sint Maarten" : "imagens_png/sx.png",
"Slovakia" : "imagens_png/sk.png",
"Slovenia" : "imagens_png/si.png",
"Solomon Islands" : "imagens_png/sb.png",
"Somalia" : "imagens_png/so.png",
"South Africa" : "imagens_png/za.png",
"South Georgia" : "imagens_png/gs.png",
"South Sudan" : "imagens_png/ss.png",
"Spain" : "imagens_png/es.png",
"Sri Lanka" : "imagens_png/lk.png",
"Sudan" : "imagens_png/sd.png",
"Suriname" : "imagens_png/sr.png",
"Svalbard and Jan Mayen" : "imagens_png/sj.png",
"Sweden" : "imagens_png/se.png",
"Switzerland" : "imagens_png/ch.png",
"Syria" : "imagens_png/sy.png",
"Taiwan" : "imagens_png/tw.png",
"Tajikistan" : "imagens_png/tj.png",
"Tanzania" : "imagens_png/tz.png",
"Thailand" : "imagens_png/th.png",
"Timor-Leste" : "imagens_png/tl.png",
"Togo" : "imagens_png/tg.png",
"Tokelau" : "imagens_png/tk.png",
"Tonga" : "imagens_png/to.png",
"Trinidad and Tobago" : "imagens_png/tt.png",
"Tunisia" : "imagens_png/tn.png",
"Turkey" : "imagens_png/tr.png",
"Turkmenistan" : "imagens_png/tm.png",
"Turks and Caicos Islands" : "imagens_png/tc.png",
"Tuvalu" : "imagens_png/tv.png",
"Uganda" : "imagens_png/ug.png",
"Ukraine" : "imagens_png/ua.png",
"United Arab Emirates" : "imagens_png/ae.png",
"United Kingdom" : "imagens_png/gb.png",
"United States" : "imagens_png/us.png",
"United States Minor Outlying Islands" : "imagens_png/um.png",
"Uruguay" : "imagens_png/uy.png",
"Uzbekistan" : "imagens_png/uz.png",
"Vanuatu" : "imagens_png/vu.png",
"Vatican City (Holy See)" : "imagens_png/va.png",
"Venezuela" : "imagens_png/ve.png",
"Vietnam" : "imagens_png/vn.png",
"British Virgin Islands" : "imagens_png/vg.png",
"United States Virgin Islands" : "imagens_png/vi.png",
"Wales" : "imagens_png/gb-wls.png",
"Wallis and Futuna" : "imagens_png/wf.png",
"Western Sahara" : "imagens_png/eh.png",
"Yemen" : "imagens_png/ye.png",
"Zambia" : "imagens_png/zm.png",
"Zimbabwe" : "imagens_png/zw.png",

}

# Percorrer todas as entradas da tabela
# with transaction.atomic():  # Agrupa as operações para evitar falhas parciais
for patria in Patrias.objects.all():
    nome_normalizado = patria.nome.strip().lower()
    sigla_normalizada = patria.siglas.strip().upper() if patria.siglas else None

    for chave, caminho in bandeiras.items():
        if chave.lower() == nome_normalizado or chave.upper() == sigla_normalizada:
            print(f"Atualizando {patria.nome} -> {caminho}")  # Debug
            patria.flag = caminho
            patria.save(update_fields=['flag'])  # Garante a atualização
    
print("Atualização concluída!")                