import sys
import os
import django
# Configurar o caminho do projeto e o Django
sys.path.append("/home/carlos/Desenvolvimento/Python/Workspace/earthProject")
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'terra.settings')
django.setup()
from core.models import Patrias
# Dicionário de países e siglas
countries_and_siglas = {
    "Afghanistan" :"AF",
    "Albania" :"AL",
    "Algeria" :"DZ",
    "American Samoa" : "AS",
    "Andorra" :"AD",
    "Angola" :"AO",
    "Anguilla" : "",
    "Antigua and Barbuda" : "ATG",
    "Argentina" :"AR",
    "Armenia" :"AM",
    "Aruba" : "ARB",
    "Australia" :"AU",
    "Austria" :"AT",
    "Azerbaijan" :"AZ",
    "Bahamas" :"BS",
    "Bahrain" :"BH",
    "Bangladesh" :"BD",
    "Barbados" :"BB",
    "Belarus" :"BY",
    "Belgium" :"BE",
    "Belize" :"BZ",
    "Benin" :"BJ",
    "Bermuda" : "BM",
    "Bhutan" :"BT",
    "Bolivia" :"BO",
    "Bosnia and Herzegovina" :"BA",
    "Botswana" :"BW",
    "Brazil" :"BR",
    "British Virgin Islands" : "BVI",
    "Brunei" :"BN",
    "Bulgaria" :"BG",
    "Burkina Faso" :"BF",
    "Burundi" :"BI",
    "Cabo Verde" : "CPV",
    "Cambodia" :"KH",
    "Cameroon" :"CM",
    "Canada" :"CA",
    "Cape Verde" :"CV",
    "Caribbean Netherlands" : "BES",
    "Central African Republic" :"CF",
    "Chad" :"TD",
    "Chile" :"CL",
    "China" :"CN",
    "Colombia" :"CO",
    "Comoros" :"KM",
    "Congo (Congo-Brazzaville)" :"CG",
    "Cook Islands" : "CK",
    "Costa Rica" :"CR",
    "Côte d'Ivoire" : "CI",
    "Croatia" :"HR",
    "Cuba" :"CU",
    "Curaçao" : "CW",
    "Cyprus" :"CY",
    "Czech Republic (Czechia)" :"CZ",
    "DR Congo" :"CD",
    "Denmark" :"DK",
    "Djibouti" :"DJ  ",
    "Dominica" :"DM",
    "Dominican Republic" : " DO",
    "Ecuador" :"EC",
    "Egypt" :"EG",
    "El Salvador" :"SV",
    "Equatorial Guinea" :"GQ",
    "Eritrea" :"ER",
    "Estonia" :"EE",
    "Eswatini (Swaziland)" :"SZ",
    "Ethiopia" :"ET",
    "Faeroe Islands" : "FO",
    "Falkland Islands" : "FK",
    "Fiji" :"FJ",
    "Finland" :"FI",
    "France" :"FR",
    "French Guiana" : "GF",
    "French Polynesia" : "PF",
    "Gabon" :"GA",
    "Gambia" :"GM",
    "Georgia" :"GE",
    "Germany" :"DE",
    "Gibraltar" : "GIB",
    "Ghana" :"GH",
    "Greece" :"GR",
    "Greenland" : "GL",
    "Grenada" : "GD",
    "Guadeloupe" : "GP",
    "Guam" : "GU",
    "Guatemala" :"GT",
    "Guinea" :"GN",
    "Guinea-Bissau" :"GW",
    "Guyana" :"GY",
    "Haiti" :"HT",
    "Holy See" : "VA", 
    "Honduras" :"HN",
    "Hong Kong" : "HK",
    "Hungary" :"HU",
    "Iceland" :"IS",
    "India" :"IN",
    "Indonesia" :"ID",
    "Iran" :"IR",
    "Iraq" :"IQ",
    "Ireland" :"IE",
    "Isle of Man" : "IM",
    "Israel" :"IL",
    "Italy" :"IT",
    "Ivory Coast" :"CI",
    "Jamaica" :"JM",
    "Japan" :"JP",
    "Jordan" :"JO",
    "Kazakhstan" :"KZ",
    "Kenya" :"KE",
    "Kiribati" :"KI",
    "Kuwait" :"KW",
    "Kyrgyzstan" :"KG",
    "Laos" :"LA",
    "Latvia" :"LV",
    "Lebanon" :"LB",
    "Lesotho" :"LS",
    "Liberia" :"LR",
    "Libya" :"LY",
    "Liechtenstein" :"LI",
    "Lithuania" :"LT",
    "Luxembourg" :"LU",
    "Macao" : "MO",
    "Madagascar" :"MG",
    "Malawi" :"MW",
    "Malaysia" :"MY",
    "Maldives" :"MV",
    "Mali" :"ML",
    "Malta" :"MT",
    "Marshall Islands" : "RMI",
    "Martinique" : "MQ",
    "Mauritania" : "MR",
    "Mauritius" : "MU",
    "Mayotte" : "YT",
    "Mexico" :"MX",
    "Micronesia" : "FSM",
    "Monaco" :"MC",
    "Mongolia" :"MN",
    "Montenegro" :"ME",
    "Montserrat" : "MS",
    "Morocco" :"MA",
    "Moldova" : "MD",
    "Mozambique" :"MZ",
    "Myanmar" :"MM",
    "Namibia" :"NA",
    "Nauru" :"NR",
    "Nepal" :"NP",
    "Netherlands" :"NL",
    "New Caledonia" : "NC",
    "New Zealand" :"NZ",
    "Nicaragua" :"NI",
    "Niger" :"NE",
    "Nigeria" :"NG",
    "North Korea" :"KP",
    "North Macedonia" :"MK",
    "Northern Mariana Islands" : "CNMI",
    "Norway" :"NO",
    "Niue" : "NU",
    "Oman" :"OM",
    "Pakistan" :"PK",
    "Palau" :"PW",
    "Panama" :"PA",
    "Papua New Guinea" :"PG",
    "Paraguay" :"PY",
    "Peru" :"PE",
    "Philippines" :"PH",
    "Poland" :"PL",
    "Portugal" :"PT",
    "Puerto Rico" : "PR",
    "Qatar" :"QA",
    "Réunion" : "RE",
    "Romania" :"RO",
    "Russia" :"RU",
    "Rwanda" :"RW",
    "Saint Barthelemy" : "St. Barth",
    "Saint Helena" : "STHL",
    "Saint Kitts and Nevis" :"STCN",
    "Saint Lucia" :"LC",
    "Saint Martin" : "SXM",
    "Saint Pierre & Miquelon" : "PM",
    "Saint Vincent and the Grenadines" :"VC",
    "Samoa" :"WS",
    "San Marino" :"SM",
    "Sao Tome & Principe" :"STP",
    "Saudi Arabia" :"SA",
    "Senegal" :"SN",
    "Serbia" :"RS",
    "Seychelles" :"SC",
    "Sierra Leone" :"SL",
    "Singapore" :"SG",
    "Sint Maarten" : "SX",
    "Slovakia" :"SK",
    "Slovenia" :"SI",
    "Solomon Islands" :"SB",
    "Somalia" :"SO",
    "South Africa" :"ZA",
    "South Korea" :"KR",
    "South Sudan" :"SS",
    "Spain" :"ES",
    "Sri Lanka" :"LK",
    "St. Vincent & Grenadines" : "SVG",
    "State of Palestine" : "PS",
    "Sudan" :"SD",
    "Suriname" :"SR",
    "Sweden" :"SE",
    "Switzerland" :"CH",
    "Syria" :"SY",
    "Taiwan" :"TW",
    "Tajikistan" :"TJ",
    "Tanzania" :"TZ",
    "Thailand" :"TH",
    "Timor-Leste" :"TL",
    "Togo" :"TG",
    "Tokelau" : "TK",
    "Tonga" :"TO",
    "Trinidad and Tobago" :"TT",
    "Tunisia" :"TN",
    "Turkey" :"TR",
    "Turkmenistan" :"TM",
    "Turks and Caicos" : "TCI",
    "Tuvalu" :"TV",
    "Uganda" :"UG",
    "Ukraine" :"UA",
    "United Arab Emirates" :"AE",
    "United Kingdom" : 	" GB",
    "United States" :"US",
    "Uruguay" :"UY",
    "U.S. Virgin Islands" : "USVI",
    "Uzbekistan" :"UZ",
    "Vanuatu" :"VU",
    "Vatican City" :"VA",
    "Venezuela" :"VE",
    "Vietnam" :"VN",
    "Wallis & Futuna" : "WF",
    "Western Sahara" : "MINURSO",
    "Yemen" :"YE",
    "Zambia" :"ZM",
    "Zimbabwe" :"ZW",

}

def update_siglas():
    print("[INFO] Iniciando a atualização das siglas...")
    total_atualizado = 0
    total_nao_encontrado = 0
    
    # Busca todos os registros da tabela 'Patrias'
    for patria in Patrias.objects.all():
        # Verifica se o nome de um país está no dicionário
        siglas = countries_and_siglas.get(patria.nome)
        if siglas:
            patria.siglas = siglas
            patria.save() # Salva a alteração no banco de dados
            total_atualizado += 1
            print(f"[INFO] Sigla atualizado: {patria.nome} -> {siglas}")
        else:
            total_nao_encontrado += 1
            print(f"[AVISO] País não encontrado no dicionário: {patria.nome}")
    print(f"[INFO] Atualização concluida. Siglas atualizadas: {total_atualizado}")
   
# Executa a função
update_siglas() 